#!/bin/bash

request=$1
status_code=$4

if [[ ! -f /tmp/clipboard-server/upload-list.txt ]]; then
    printf 428 > "$status_code"
    exit
fi

method=$(head -1 "$request" | awk '{ print $1 }')
if [[ "$method" != "PUT" ]]; then
    printf 405 > "$status_code"
    exit
fi

content_length=$(grep Content-Length "$request" | cut -d' ' -f2)
upload_id=$(grep Upload-Id "$request" | cut -d' ' -f2)
chunk_index=$(grep Chunk-Index "$request" | cut -d' ' -f2)

entry=$(grep "^$upload_id"$'\t' /tmp/clipboard-server/upload-list.txt 2>/dev/null)
if [[ $? -ne 0 ]]; then
    printf 412 > "$status_code"
    exit
fi

if [[ ! "$chunk_index" =~ ^[0-9]+$ ]]; then
    printf 400 > "$status_code"
    exit
fi

filename=$(echo "$entry" | cut -d$'\t' -f2)
n_chunks=$(echo "$entry" | cut -d$'\t' -f4)

if [[ ! "$chunk_index" -lt "$n_chunks" ]]; then
    printf 400 > "$status_code"
    exit
fi

partfile=/tmp/clipboard-server/"$filename"."$upload_id"."$chunk_index"
dd ibs=1 count="$content_length" of="$partfile" 2>/dev/null

received_size=$(stat -c %s "$partfile")
if [[ $received_size -ne $content_length ]]; then
    printf 408 > "$status_code"
    exit
fi

printf 200 > "$status_code"
