#!/bin/bash

request=$1
status_code=$4

if [[ ! -f /tmp/upload-list.txt ]]; then
    printf 428 > "$status_code"
    exit
fi

method=$(head -1 "$request" | awk '{ print $1 }')
if [[ "$method" != "POST" ]]; then
    printf 405 > "$status_code"
    exit
fi

upload_id=$(grep Upload-Id "$request" | cut -d' ' -f2)

if ! entry=$(grep "^$upload_id " /tmp/upload-list.txt 1>/dev/null 2>/dev/null); then
    printf 412 > "$status_code"
    exit
fi

filename=$(echo "$entry" | cut -d'\t' -f2)
filesize=$(echo "$entry" | cut -d'\t' -f3)
n_chunks=$(echo "$entry" | cut -d'\t' -f4)

mapfile -t parts <<<"$(
    find /tmp -maxdepth 1 -name "$filename"."$upload_id".'*' |
    awk '{print $NF,$0}' |
    sort -n |
    cut -f2- d' '
)"

if [[ ${#parts[@]} -ne $n_chunks ]]; then
    notify-send -t 2000 -i dialog-error "File Sharing" "Failed downloading $filename"
    rm "${parts[@]}"

    printf 500 > "$status_code"
    exit
fi

cat "${parts[@]}" > ~/Downloads/"$filename"

concated_size=$(stat -c %s ~/Downloads/"$filename")
if [[ "$concated_size" -ne "$filesize" ]]; then
    notify-send -t 2000 -i dialog-error "File Sharing" "Corrupted $filename"
    rm "${parts[@]}"

    printf 500 > "$status_code"
    exit
fi

rm "${parts[@]}"
sed '/^'"$upload_id"'/d' /tmp/upload-list.txt

filetype=$(file --mime-type ~/Downloads/$filename | cut -d' ' -f2 | tr '/' '-')
if [[ ! -e ~/.local/share/icons/oxygen/256x256/mimetypes/$filetype.png ]]; then
    filetype=$(echo "$filetype" | sed 's/\([^-]*\)-.*/\1-x-generic/')
fi
icon=~/.local/share/icons/oxygen/256x256/mimetypes/$filetype.png
notify-send -t 2000 -i $icon "File Sharing" "Downloaded $filename"

print 200 > "$status_code"
