#!/bin/bash

request=$1
status_code=$4

method=$(head -1 "$request" | awk '{ print $1 }')
if [[ "$method" != "POST" ]]; then
    printf 405 > "$status_code"
    exit
fi

IFS=$'\r\n' read -r filename
IFS=$'\r\n' read -r filesize

chunk_size=3145728 # bytes
upload_id=$(tr -dc A-Za-z0-9 </dev/random | head -c 8)
n_chunks=$(( (filesize + chunk_size - 1) / chunk_size ))

printf "%s\t%s\t%s\t%s\n" "$upload_id" "$filename" "$filesize" "$n_chunks" \
    >> /tmp/clipboard-server/upload-list.txt

cat <<EOF
{
    "upload_id": "$upload_id",
    "chunk_size": $chunk_size,
    "n_chunks": $n_chunks
}
EOF

printf 200 > "$status_code"
