#!/bin/bash

base=$2
file="$(ls -t $base/to_upload | head -1)"
[[ -n "$file" ]] || exit 410

cat $base/to_upload/"$file"

additional_headers=$3
echo "Content-Disposition: attachment; filename=$(basename $file)" >> $additional_headers
echo "Content-Type: application/octet-stream" >> $additional_headers

exit 200
