#!/bin/bash

request=$1
status_code=$4

method=$(head -1 "$request" | awk '{ print $1 }')
content_length=$(grep Content-Length "$request" | cut -d' ' -f2)

IFS= read -rd $'\r\n' boundary && read
IFS= read -rd $'\r\n' content_disposition && read
IFS= read -rd $'\r\n' content_type && read
IFS= read -rd $'\r\n' && read

header_length=$(
    printf "%s\r\n%s\r\n%s\r\n\r\n" \
        "$boundary" \
        "$content_disposition" \
        "$content_type" | wc -c)

footer_length=$(printf "\r\n%s--\r\n" "$boundary" | wc -c)

((content_length -= $header_length + $footer_length))

filename=$(echo "$content_disposition" | sed 's/.*filename="\(.*\)"/\1/')

dd ibs=1 count=$content_length of=~/Downloads/"$filename" 2>/dev/null

received_size=$(stat -c %s ~/Downloads/"$filename")

if [[ $received_size -ne $content_length ]]; then
    notify-send -t 2000 -i dialog-error "File Sharing" "Failed downloading $filename"
    rm ~/Downloads/"$filename"
    printf 400 > "$status_code"
    exit
fi

filetype=$(printf "%s" "$content_type" | cut -d' ' -f2 | tr '/' '-')
if [[ ! -e ~/.local/share/icons/oxygen/256x256/mimetypes/$filetype.png ]]; then
    filetype=$(echo "$filetype" | sed 's/\([^-]*\)-.*/\1-x-generic/')
fi
icon=~/.local/share/icons/oxygen/256x256/mimetypes/$filetype.png
notify-send -t 2000 -i $icon "File Sharing" "Downloaded $filename to ~/Downloads folder"

printf 200 > "$status_code"
